"use client";
// import type { Metadata } from "next";
import { Outfit, Playfair_Display } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import CursorFollower from "@/components/CursorFollower";

const playfair = Playfair_Display({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: "--font-playfair-display",
});

const outfit = Outfit({
  weight: ['300', '400', '600', '700', '800', '900'],
  style: ['normal',],
  subsets: ['latin'],
  variable: "--font-outfit",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${playfair.variable} ${outfit.variable}`}>
        <ThemeProvider

          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <CursorFollower />

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
